---
  # dependency
  - name: Install pycurl dep
    sudo: yes
    apt: pkg=python-pycurl update_cache=yes state=latest

  - name: Add docker apt repository key
    sudo: yes
    shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

  - name: Add docker apt repository
    sudo: yes
    apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

  - name: Install latest docker via apt
    sudo: yes
    apt: pkg=lxc-docker state=latest update_cache=yes
