---
  # dependency
  - name: Install pycurl dep
    sudo: True
    apt: pkg=python-pycurl update_cache=yes state=latest

#  - name: Add Docker Key
#    sudo: True
#    apt_key: url=https://get.docker.io/gpg state=present
#
#  - name: Add Docker Repo
#    sudo: True
#    apt_repository: repo='deb https://get.docker.io/ubuntu docker main' update_cache=yes state=present
#
#  - name: Install Docker
#    sudo: True
#    apt: pkg=lxc-docker update_cache=yes state=latest
#

  - name: Add docker apt repository key
    apt_key: url=https://get.docker.io/gpg state=present
  - name: Add docker apt repository
    apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
  - name: Install latest docker via apt
    apt: pkg=lxc-docker state=latest update_cache=yes
