---
  - name: Add Docker key
    sudo: True
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

  - name: Add Docker repo
    sudo: True
    command: "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"

  - name: Install Docker
    sudo: True
    apt: pkg=lxc-docker state=latest update_cache=yes

